name: munchkin_killometer
description: munchkin kill-o-meter flutter app

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  swipedetector: ^1.2.0
  badges: ^0.0.6

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

# run 'flutter packages pub run flutter_launcher_icons:main' to override basic android icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
  - assets/munch.png

  fonts:
  - family:  CustomIcons
    fonts:
    - asset: fonts/CustomIcons.ttf
  - family:  MunchkinFonts
    fonts:
    - asset: fonts/Windlass.ttf
